services:
  nginx:
    container_name: nginx_proxy
    image: nginx:alpine
    restart: always
    ports:
      - "5085:5005"
      - "5006:5006" # Expose FastAPI server port for penetration testing
      - "8080:8080" # Velocity front
      - "4242:4242" # Velocity back
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - stripe_static:/staticfiles
      - stripe_media:/media
      - velocity_static:/velocity
    depends_on:
      - stripe-app
    networks:
      - web_network
  stripe-app:
    container_name: stripe_app
    restart: always
    build: ./stripe-app
    environment:
      - DEBUG=True
      - STRIPE_SECRET_KEY=${STRIPE_SECRET_KEY}
      - STRIPE_PUBLISHABLE_KEY=${STRIPE_PUBLISHABLE_KEY}
    networks:
      - web_network
      - db_network
    volumes:
      - stripe_media:/media
      - stripe_static:/staticfiles
  fastapi-server:
    container_name: fastapi_server
    restart: always
    build: ./fastapi-server
    networks:
      - web_network
      - db_network
  velocity-front:
    container_name: velocity_front
    restart: always
    build: ./velocity-front
    networks:
      - web_network
    volumes:
      - velocity_static:/usr/share/nginx/html
  velocity-back:
    container_name: velocity_back
    restart: always
    build: ./velocity-back
    networks:
      - web_network
      - db_network

networks:
  web_network:
    driver: bridge
  db_network:
    driver: bridge

volumes:
  stripe_media:
  stripe_static:
  velocity_static: